[platformio]
src_dir = .
default_envs = esp32
core_dir = .pio

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200

lib_ldf_mode = chain
lib_compat_mode = off

board_build.partitions = partitions.csv
board_build.filesystem = littlefs

build_src_filter =
  +<src/*.cpp>

lib_deps =
  knolleary/PubSubClient@^2.8

build_flags =
  -I src/

[env:esp32]
board = esp32dev
upload_protocol = espota
upload_flags = -a${sysenv.OTA_PASSWORD}
